kind = "web"
previewPath = "/"
title = "VAPT Bolão Copa 2026"
version = "1.0.0"
id = "artifacts/vapt-bolao"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22477

[services.development]
run = "pnpm --filter @workspace/vapt-bolao run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/vapt-bolao", "run", "build" ]
publicDir = "artifacts/vapt-bolao/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22477"
BASE_PATH = "/"
